name: Population Zero
favicon: null
layout_spectrum: 0.66091
typography_spectrum: 1
title: Population Zero
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2d1910'
    - '#faf6eb'
    - '#beb7a5'
    - '#85806d'
    - '#c44234'
  brandStrength: 1
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
